# Generated by Django 5.0.6 on 2024-06-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_news_request_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_url',
        ),
    ]
